# Generated by Django 4.2 on 2023-04-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resident",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("birthday", models.DateField()),
                ("admission_date", models.DateField()),
                ("rent", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
