# Generated by Django 4.2 on 2023-04-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bill_auto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="discharge_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
