# Generated by Django 4.2 on 2023-04-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bill_auto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="Resident",
            name="discharge_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
